// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type Schedule struct {
	ID       int64  `json:"id"`
	Userid   string `json:"userid"`
	Day      string `json:"day"`
	Clockin  string `json:"clockin"`
	Clockout string `json:"clockout"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}
