// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Employee struct {
	ID     int64
	Name   string
	RoleID sql.NullInt64
}

type Role struct {
	ID   int64
	Name string
}

type Schedule struct {
	ID         int64
	EmployeeID sql.NullInt64
	DayOfWeek  sql.NullInt64
	ClockIn    sql.NullString
	ClockOut   sql.NullString
}
