// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type Employee struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	RoleID int64  `json:"role_id"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Schedule struct {
	ID         int64  `json:"id"`
	EmployeeID string `json:"employee_id"`
	DayOfWeek  int64  `json:"day_of_week"`
	ClockIn    string `json:"clock_in"`
	ClockOut   string `json:"clock_out"`
}
